-- Step 2b: demo illustrations for built-in exercises, with the credit their license requires.
-- GENERATED by scripts/build-exercise-media-migration.mjs from supabase/seed-data/wger-images.json.
-- Images: Everkinetic / wger.de line art via wger (CC-BY-SA), stored unmodified in
-- exercise-media/builtin/.

-- { author, author_url?, license, license_url, source_url } for third-party media; null otherwise.
alter table public.exercises
  add column if not exists media_credit jsonb
  check (media_credit is null or jsonb_typeof(media_credit) = 'object');

-- Every signed-in user can read built-in media. Nobody but the service role writes there: the
-- insert/update/delete policies only match a folder named after the caller's own user id.
create policy "exercise-media: read built-in" on storage.objects
  for select to authenticated
  using (bucket_id = 'exercise-media' and (storage.foldername(name))[1] = 'builtin');

update public.exercises e
set thumbnail_url = v.path, media_credit = v.credit
from (values
  ('back extension', 'builtin/back-extension.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/301/view/hyperextensions"}'::jsonb),
  ('barbell curl', 'builtin/barbell-curl.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/91/view/biceps-curls-with-barbell"}'::jsonb),
  ('barbell row', 'builtin/barbell-row.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/83/view/bent-over-rowing"}'::jsonb),
  ('barbell shrug', 'builtin/barbell-shrug.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/571/view/shrugs-barbells"}'::jsonb),
  ('bench dip', 'builtin/bench-dip.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/197/view/dips-between-two-benches"}'::jsonb),
  ('bench press', 'builtin/bench-press.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/73/view/bench-press"}'::jsonb),
  ('cable curl', 'builtin/cable-curl.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/95/view/biceps-curl-with-cable"}'::jsonb),
  ('chin-up', 'builtin/chin-up.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/152/view/chin-up"}'::jsonb),
  ('close-grip bench press', 'builtin/close-grip-bench-press.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/76/view/bench-press-narrow-grip"}'::jsonb),
  ('crunch', 'builtin/crunch.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/167/view/crunches"}'::jsonb),
  ('decline bench press', 'builtin/decline-bench-press.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/185/view/decline-bench-press-barbell"}'::jsonb),
  ('dumbbell bench press', 'builtin/dumbbell-bench-press.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/75/view/benchpress-dumbbells"}'::jsonb),
  ('dumbbell curl', 'builtin/dumbbell-curl.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/92/view/biceps-curls-with-dumbbell"}'::jsonb),
  ('dumbbell shoulder press', 'builtin/dumbbell-shoulder-press.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/567/view/shoulder-press-dumbbells"}'::jsonb),
  ('dumbbell shrug', 'builtin/dumbbell-shrug.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/572/view/shrugs-dumbbells"}'::jsonb),
  ('front squat', 'builtin/front-squat.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/257/view/front-squats"}'::jsonb),
  ('good morning', 'builtin/good-morning.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/1392/view/good-morning"}'::jsonb),
  ('hammer curl', 'builtin/hammer-curl.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/272/view/hammer-curls"}'::jsonb),
  ('incline bench press', 'builtin/incline-bench-press.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/538/view/incline-bench-press-barbell"}'::jsonb),
  ('incline dumbbell press', 'builtin/incline-dumbbell-press.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/537/view/incline-bench-press-dumbbell"}'::jsonb),
  ('lateral raise', 'builtin/lateral-raise.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/348/view/lateral-raises"}'::jsonb),
  ('lying leg curl', 'builtin/lying-leg-curl.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/365/view/leg-curls-laying"}'::jsonb),
  ('machine shoulder press', 'builtin/machine-shoulder-press.png', '{"author":"wger.de","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/543/view/shoulder-press-on-machine"}'::jsonb),
  ('pec deck', 'builtin/pec-deck.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/135/view/butterfly"}'::jsonb),
  ('preacher curl', 'builtin/preacher-curl.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/465/view/preacher-curls"}'::jsonb),
  ('rack pull', 'builtin/rack-pull.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/484/view/rack-deadlift"}'::jsonb),
  ('rope hammer curl', 'builtin/rope-hammer-curl.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/275/view/hammercurls-on-cable"}'::jsonb),
  ('seated cable row', 'builtin/seated-cable-row.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/394/view/long-pulley-low-row"}'::jsonb),
  ('seated leg curl', 'builtin/seated-leg-curl.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/366/view/leg-curls-sitting"}'::jsonb),
  ('skull crusher', 'builtin/skull-crusher.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/246/view/skullcrusher-sz-bar"}'::jsonb),
  ('smith machine incline press', 'builtin/smith-machine-incline-press.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/539/view/incline-bench-press-mp"}'::jsonb),
  ('T-bar row', 'builtin/t-bar-row.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/513/view/rowing-t-bar"}'::jsonb),
  ('walking lunge', 'builtin/walking-lunge.png', '{"author":"Everkinetic","license":"CC-BY-SA 3","license_url":"https://creativecommons.org/licenses/by-sa/3.0/deed.en","source_url":"https://wger.de/en/exercise/206/view/dumbbell-lunges-walking"}'::jsonb)
) as v (name, path, credit)
where e.owner_id is null and e.name = v.name;
